# Generated by Django 3.1.1 on 2020-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('coliber', models.CharField(max_length=15)),
                ('make_country', models.CharField(max_length=15)),
            ],
        ),
    ]
