# Generated by Django 3.1.1 on 2020-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='year_invented',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gun',
            name='coliber',
            field=models.FloatField(default=0),
        ),
    ]
