# Generated by Django 3.1.2 on 2021-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href_user', models.CharField(max_length=300)),
                ('many_to_many_field', models.ManyToManyField(max_length=100, to='app.book')),
            ],
        ),
    ]
